import { Resend } from 'resend';
import { ProcessedArticle } from './ai-briefing';
import { categoryLabels } from './feeds';

const resend = new Resend(process.env.RESEND_API_KEY);

interface DigestEmailProps {
  articles: ProcessedArticle[];
  digestIntro: string;
  date: Date;
}

function groupByCategory(
  articles: ProcessedArticle[]
): Record<string, ProcessedArticle[]> {
  return articles.reduce(
    (acc, article) => {
      const cat = article.category;
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(article);
      return acc;
    },
    {} as Record<string, ProcessedArticle[]>
  );
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function generateEmailHTML({
  articles,
  digestIntro,
  date,
}: DigestEmailProps): string {
  const grouped = groupByCategory(articles);

  const categoryBlocks = Object.entries(grouped)
    .map(([category, categoryArticles]) => {
      const label =
        categoryLabels[category as keyof typeof categoryLabels] || category;

      const articleBlocks = categoryArticles
        .slice(0, 10) // Limit per category
        .map(
          (article) => `
        <div style="margin-bottom: 24px; padding-bottom: 24px; border-bottom: 1px solid #e5e7eb;">
          <h3 style="margin: 0 0 8px 0; font-size: 18px;">
            <a href="${article.url}" style="color: #1a1a1a; text-decoration: none;">${article.title}</a>
          </h3>
          <p style="margin: 0 0 8px 0; font-size: 12px; color: #6b7280;">
            ${article.sourceName} · ${article.publishedAt.toLocaleDateString()}
          </p>
          <p style="margin: 0 0 12px 0; color: #374151; line-height: 1.6;">
            ${article.briefing || article.summary}
          </p>
          ${
            article.tags.length > 0
              ? `<p style="margin: 0; font-size: 12px;">
              ${article.tags.map((tag) => `<span style="background: #f3f4f6; padding: 2px 8px; border-radius: 4px; margin-right: 4px;">${tag}</span>`).join('')}
            </p>`
              : ''
          }
          ${
            article.contentAngles.length > 0
              ? `<div style="margin-top: 12px; padding: 12px; background: #fef3c7; border-radius: 6px;">
              <p style="margin: 0 0 4px 0; font-size: 12px; font-weight: 600; color: #92400e;">💡 Content Angles:</p>
              <ul style="margin: 0; padding-left: 16px; font-size: 13px; color: #78350f;">
                ${article.contentAngles.map((angle) => `<li>${angle}</li>`).join('')}
              </ul>
            </div>`
              : ''
          }
        </div>
      `
        )
        .join('');

      return `
        <div style="margin-bottom: 32px;">
          <h2 style="font-size: 20px; color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 20px;">
            ${label}
          </h2>
          ${articleBlocks}
        </div>
      `;
    })
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 20px; background: #ffffff;">
  
  <div style="text-align: center; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 1px solid #e5e7eb;">
    <h1 style="margin: 0 0 8px 0; font-size: 28px; color: #1a1a1a;">📰 Daily Digest</h1>
    <p style="margin: 0; color: #6b7280; font-size: 14px;">${formatDate(date)}</p>
  </div>

  <div style="background: #eff6ff; padding: 20px; border-radius: 8px; margin-bottom: 32px; border-left: 4px solid #3b82f6;">
    <h2 style="margin: 0 0 12px 0; font-size: 16px; color: #1e40af;">Today's Overview</h2>
    <div style="color: #1e3a5f; line-height: 1.7; white-space: pre-wrap;">${digestIntro}</div>
  </div>

  <p style="color: #6b7280; font-size: 14px; margin-bottom: 24px;">
    Found <strong>${articles.length} articles</strong> from the last 24 hours across ${Object.keys(grouped).length} categories.
  </p>

  ${categoryBlocks}

  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px;">
    <p>Generated by your RSS Aggregator</p>
    <p><a href="${process.env.DASHBOARD_URL || '#'}" style="color: #3b82f6;">View full archive →</a></p>
  </div>

</body>
</html>
  `;
}

function generatePlainText({
  articles,
  digestIntro,
  date,
}: DigestEmailProps): string {
  const grouped = groupByCategory(articles);

  let text = `DAILY DIGEST - ${formatDate(date)}\n\n`;
  text += `TODAY'S OVERVIEW\n${digestIntro}\n\n`;
  text += `Found ${articles.length} articles from the last 24 hours.\n\n`;
  text += '='.repeat(50) + '\n\n';

  Object.entries(grouped).forEach(([category, categoryArticles]) => {
    const label =
      categoryLabels[category as keyof typeof categoryLabels] || category;
    text += `${label.toUpperCase()}\n${'─'.repeat(30)}\n\n`;

    categoryArticles.slice(0, 10).forEach((article) => {
      text += `${article.title}\n`;
      text += `${article.sourceName} · ${article.publishedAt.toLocaleDateString()}\n`;
      text += `${article.url}\n\n`;
      text += `${article.briefing || article.summary}\n\n`;
      if (article.contentAngles.length > 0) {
        text += `Content Angles:\n`;
        article.contentAngles.forEach((angle) => {
          text += `  • ${angle}\n`;
        });
        text += '\n';
      }
      text += '─'.repeat(30) + '\n\n';
    });
  });

  return text;
}

export async function sendDigestEmail(
  articles: ProcessedArticle[],
  digestIntro: string,
  recipientEmail: string
): Promise<{ success: boolean; error?: string }> {
  const date = new Date();

  const emailProps: DigestEmailProps = {
    articles,
    digestIntro,
    date,
  };

  try {
    const { error } = await resend.emails.send({
      from: process.env.EMAIL_FROM || 'Daily Digest <digest@yourdomain.com>',
      to: recipientEmail,
      subject: `📰 Daily Digest - ${formatDate(date)}`,
      html: generateEmailHTML(emailProps),
      text: generatePlainText(emailProps),
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (error) {
    console.error('Failed to send email:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}
